version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: transaction_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactiondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/transactiondb
    command: sh -c "pytest app/tests/transaction_test.py"

  fastapi:
    build: .
    container_name: transaction_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/transactiondb
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
